# Generated by Django 2.1.5 on 2019-02-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='users_lik',
            new_name='users_like',
        ),
    ]
